#!/bin/bash

if [[ $1 == 'enable' ]]
then
    echo 'enabling fullcharge, remember to disable'
    echo 99 | sudo tee /sys/class/power_supply/BAT0/charge_stop_threshold
    echo 97 | sudo tee /sys/class/power_supply/BAT0/charge_start_threshold
elif [[ $1 == 'disable' ]]
then
    echo 'disabling fullcharge'
    echo 85 | sudo tee /sys/class/power_supply/BAT0/charge_start_threshold
    echo 90 | sudo tee /sys/class/power_supply/BAT0/charge_stop_threshold
else
    echo 'Usage: fullcharge < enable | disable >'
    exit 1
fi
